#**NUMPY**

Class name of numpy is ndarray

Numpy is a python library used for working with arrays

In python we have lists that seves the purpose of arrays, but they are slow to process.

Numpy aims to provide an array object that is up to 50* faster than traditional python lists.


The array object is Numpy is called ndarray ,it provieds a lot of supporting functions that  make working with ndarray very easy

Arrays are very frequently used in dta science ,where speed and resource are very importantcollection of homogeneous data

it does not support hetrogeneous data size is fixed

In [ ]:
import numpy as np

In [ ]:
import numpy as np

x = np.ndarray([1,2,4,5])

print(x)

[[[[4.69828075e-310 0.00000000e+000 1.42290906e-321             nan
    1.17339159e+214]
   [2.64521814e+185 7.48276248e+247 1.10640016e+200 1.27802877e-152
    5.38946556e+228]
   [2.90017486e+006 1.22602165e-259 9.39453289e-154 1.27850768e-152
    6.83355565e-140]
   [1.17338167e+214 2.21210382e+214 3.94357072e+180 3.93379758e-085
    6.20758939e+276]]

  [[5.12259619e+231 3.65300226e+233 1.30450804e+243 1.96842614e-153
    3.04499742e+169]
   [1.96393338e-152 6.72796256e+199 7.74412839e+228 1.14281919e+243
    7.09362551e-260]
   [3.68777427e+180 2.35118036e+251 1.21790868e-152 4.18233513e+180
    1.09011303e+223]
   [8.81950740e+199 9.48999507e+189 5.73793734e+169 6.84979141e+180
    1.31608292e-259]]]]


In [ ]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])

print(x)

[1 2 3 4 5]


In [ ]:
print(type(x))

<class 'numpy.ndarray'>


In [ ]:
print(x.ndim)

4


In [ ]:
print(x.shape)

(5,)


In [ ]:
import numpy as np

x = np.array([[1, 2, 3, 4], [6, 7, 8, 9]])

print(x)
print(x.shape)
print(x.ndim)

[[1 2 3 4]
 [6 7 8 9]]
(2, 4)
2


In [ ]:
import numpy as np

x = np.array([[1,3,5,7,9],[2,4,6,8,10],[1,1,1,1,1],[1,2,3,4,5]])

print(x)
print(x.shape)
print(x.ndim)

[[ 1  3  5  7  9]
 [ 2  4  6  8 10]
 [ 1  1  1  1  1]
 [ 1  2  3  4  5]]
(4, 5)
2


In [ ]:
import numpy as np

x = np.array([[1,2,3,44,7,8],[1,2,3,4,5,6]])

print(x)
print(x.shape)
print(x.ndim)

[[ 1  2  3 44  7  8]
 [ 1  2  3  4  5  6]]
(2, 6)
2


In [ ]:
x = np.array([[[2,4,5],[7,17,30]],[[2,4,5],[7,17,30]]])
print(x)
print(type(x))
print(x.shape)
print(x.ndim)

[[[ 2  4  5]
  [ 7 17 30]]

 [[ 2  4  5]
  [ 7 17 30]]]
<class 'numpy.ndarray'>
(2, 2, 3)
3


In [ ]:
#(2,4,2)

x = np.array([[[2,4],[7,17],[2,3],[4,7]],[[2,4],[3,6],[2,4],[7,17]]])
print(x)
print(type(x))
print(x.shape)
print(x.ndim)

[[[ 2  4]
  [ 7 17]
  [ 2  3]
  [ 4  7]]

 [[ 2  4]
  [ 3  6]
  [ 2  4]
  [ 7 17]]]
<class 'numpy.ndarray'>
(2, 4, 2)
3


In [ ]:
#(3,2,3)

x = np.array([[[2,4,3],[7,17,4]],[[2,4,4],[3,6,5]],[[1,2,3],[3,4,5]]])
print(x)
print(type(x))
print(x.shape)
print(x.ndim)

[[[ 2  4  3]
  [ 7 17  4]]

 [[ 2  4  4]
  [ 3  6  5]]

 [[ 1  2  3]
  [ 3  4  5]]]
<class 'numpy.ndarray'>
(3, 2, 3)
3


In [ ]:
#(4,2,2)

x = np.array([[[2,4],[7,17]],[[2,4],[6,12]],[[2,3],[3,6]],[[1,2],[4,6]]])
print(x)
print(type(x))
print(x.shape)
print(x.ndim)

[[[ 2  4]
  [ 7 17]]

 [[ 2  4]
  [ 6 12]]

 [[ 2  3]
  [ 3  6]]

 [[ 1  2]
  [ 4  6]]]
<class 'numpy.ndarray'>
(4, 2, 2)
3


In [ ]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
np.zeros((2,3,4),dtype=int)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [ ]:
np.ones((3,2,1))

array([[[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]]])

In [ ]:
np.ones((3,2,5),dtype=int)

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [ ]:
np.arange(10,100,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [ ]:
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [ ]:
np.linspace(20,80)

array([20.        , 21.2244898 , 22.44897959, 23.67346939, 24.89795918,
       26.12244898, 27.34693878, 28.57142857, 29.79591837, 31.02040816,
       32.24489796, 33.46938776, 34.69387755, 35.91836735, 37.14285714,
       38.36734694, 39.59183673, 40.81632653, 42.04081633, 43.26530612,
       44.48979592, 45.71428571, 46.93877551, 48.16326531, 49.3877551 ,
       50.6122449 , 51.83673469, 53.06122449, 54.28571429, 55.51020408,
       56.73469388, 57.95918367, 59.18367347, 60.40816327, 61.63265306,
       62.85714286, 64.08163265, 65.30612245, 66.53061224, 67.75510204,
       68.97959184, 70.20408163, 71.42857143, 72.65306122, 73.87755102,
       75.10204082, 76.32653061, 77.55102041, 78.7755102 , 80.        ])

In [ ]:
np.full((3,4),10,dtype=int)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [ ]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.random((3,2,2))

array([[[0.8813504 , 0.77287057],
        [0.79609031, 0.22619961]],

       [[0.31142898, 0.01175465],
        [0.57045621, 0.5294433 ]],

       [[0.84234494, 0.54058732],
        [0.13038755, 0.2889914 ]]])

In [ ]:
np.random.randint(100,200,(3,2,2))

array([[[168, 114],
        [142, 154]],

       [[192, 162],
        [105, 190]],

       [[133, 183],
        [145, 162]]])

In [ ]:
np.random.randint(100,size=(3,2,2))

array([[[92,  9],
        [60,  8]],

       [[30, 47],
        [92, 47]],

       [[ 4, 68],
        [41,  0]]])

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [ ]:
#add
np.add(a,b)

array([[ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
#substract
np.subtract(a,b)

array([[-6, -6, -6],
       [-6, -6, -6]])

In [ ]:
#multiple
np.multiply(a,b)

array([[ 7, 16, 27],
       [40, 55, 72]])

In [ ]:
#division
np.divide(a,b)

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [ ]:
#power
np.power(a,b)

array([[         1,        256,      19683],
       [   1048576,   48828125, 2176782336]])

In [ ]:
import numpy as np
a = np.array([[1,2,3,4,7],[3.5,2,4.6,5.8,9.0]])

print(a)

print(a.shape)

print(a.ndim)

y = np.floor(a)

print(y)

[[1.  2.  3.  4.  7. ]
 [3.5 2.  4.6 5.8 9. ]]
(2, 5)
2
[[1. 2. 3. 4. 7.]
 [3. 2. 4. 5. 9.]]


In [ ]:
import numpy as np
a = np.array([[1,2,3,4,7],[3.5,2,4.6,5.8,9.0]])

print(a)

print(a.shape)

print(a.ndim)

y = np.ceil(a)

print(y)


[[1.  2.  3.  4.  7. ]
 [3.5 2.  4.6 5.8 9. ]]
(2, 5)
2
[[1. 2. 3. 4. 7.]
 [4. 2. 5. 6. 9.]]


In [ ]:
import numpy as np
a = np.array([[1,2,3,4,7],[3.5,2,4.6,5.8,9.0]])

print(a)

print(a.shape)

print(a.ndim)

y = np.round(a)

print(y)

[[1.  2.  3.  4.  7. ]
 [3.5 2.  4.6 5.8 9. ]]
(2, 5)
2
[[1. 2. 3. 4. 7.]
 [4. 2. 5. 6. 9.]]


In [ ]:
import numpy as np
a = np.array([[1,2,3,4,7],[3.5,2,4.6,5.8,9.0]])

print(a)

print(a.shape)

print(a.ndim)

y = np.rint(a)

print(y)

[[1.  2.  3.  4.  7. ]
 [3.5 2.  4.6 5.8 9. ]]
(2, 5)
2
[[1. 2. 3. 4. 7.]
 [4. 2. 5. 6. 9.]]


In [ ]:
import numpy as np

a = np.array([[1,2,3,4,7],[3.5,2,4.6,5.8,9.0]])

print(a)

print(type(a))




[[1.  2.  3.  4.  7. ]
 [3.5 2.  4.6 5.8 9. ]]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np

a = np.array([[1,2,3,4,7],[3.5,2,4.6,5.8,9.0]])

print(a)

print(a.dtype)


[[1.  2.  3.  4.  7. ]
 [3.5 2.  4.6 5.8 9. ]]
float64


In [ ]:
import numpy as np

a = np.array([[1,2,'3',4,7],[3.5,2,4.6,5.8,9.0]])

print(a)

print(a.dtype)


[['1' '2' '3' '4' '7']
 ['3.5' '2' '4.6' '5.8' '9.0']]
<U32


In [ ]:
import numpy as np

a = np.array([[1,2,'3',4,7],[3.5,2,4.6,5.8,9.0]])

print(a)

x = a.astype(float)

print(x)

print(x.dtype)




[['1' '2' '3' '4' '7']
 ['3.5' '2' '4.6' '5.8' '9.0']]
[[1.  2.  3.  4.  7. ]
 [3.5 2.  4.6 5.8 9. ]]
float64


In [ ]:
import numpy as np

a = np.array([[1,2,'3',4,7],[3.5,2,4.6,5.8,9.0]])

print(a)

x = a.astype(complex)

print(x)

print(a.dtype)


[['1' '2' '3' '4' '7']
 ['3.5' '2' '4.6' '5.8' '9.0']]
[[1. +0.j 2. +0.j 3. +0.j 4. +0.j 7. +0.j]
 [3.5+0.j 2. +0.j 4.6+0.j 5.8+0.j 9. +0.j]]
<U32


** **1DIMENTIONAL SUBSETTING****

In [1]:
import numpy as np

a = np.array([1,2,'3',4,7])

print(a[2])

3


** **2 DIMENTIONAL SUBSETTING** **

In [2]:
import numpy as np

a = np.array([[1,2,'3',4,7],[14,32,'30',40,22]])

print(a[1,1])

32


**t**

In [3]:
import numpy as np

a = np.array([[1,3,4,5,5],[12,22,45,77,66]])

print(a[1,2])

45


In [4]:
import numpy as np

a = np.array([[1,3,4,5,5],[12,22,45,77,66]])

print(a[1,3])

77


In [5]:
import numpy as np

a = np.array([[1,3,4,5,5],[12,22,45,77,66]])

print(a[0,3])

5


 ** **3D SUBSETTING** **

In [6]:
import numpy as np

a = np.array([[[1,3,'4',5,5],[12,22,'45',77,66]],[[12,33,'55',66,77],[1,22,'66',1007,99]]])

print(a[0,1,2])

45


** **1D SLICING** **

In [7]:
import numpy as np

a = np.array([1,3,'4',5,5])

print(a[1:4])

['3' '4' '5']


In [8]:
import numpy as np

a = np.array([1,3,4,5,5])

print(a[1:])

[3 4 5 5]


In [9]:
import numpy as np

a = np.array([1,3,4,5,7])

print(a[:4])

[1 3 4 5]


** **2D SLICING** **

In [10]:
import numpy as np

a = np.array([[1,3,4,5,5],[12,22,45,77,66]])

print(a.ndim)

#print(a)
print(a[0:2,2:5])     #0th and 1st row and 2nd 3rd 4th columns

print(a[ : ,1:3])     #0th and 1st row and 1st and 2nd columns

2
[[ 4  5  5]
 [45 77 66]]
[[ 3  4]
 [22 45]]


** **3D SLICING** **

In [11]:
import numpy as np

a = np.array([[[1,3,4,5,5],[12,22,45,77,66]],[[1,14,25,17,88],[33,44,55,66,77]]])

print(a[: ,1,2:5])

[[45 77 66]
 [55 66 77]]


In [12]:
import numpy as np

a = np.array([[[1,3,4,5,5],[12,22,45,77,66]],[[1,14,25,17,88],[33,44,55,66,77]]])

print(a[: , : ,1:4])

[[[ 3  4  5]
  [22 45 77]]

 [[14 25 17]
  [44 55 66]]]


**BOOLEAN INDEXING**

In [13]:
import numpy as np

a = np.array([[[1,3,4,5,5],[12,22,45,77,66]],[[1,14,25,17,88],[33,44,55,66,77]]])

print(a)
print(a.ndim)
print(a.shape)

[[[ 1  3  4  5  5]
  [12 22 45 77 66]]

 [[ 1 14 25 17 88]
  [33 44 55 66 77]]]
3
(2, 2, 5)


In [14]:
b = a>10

print(b)

[[[False False False False False]
  [ True  True  True  True  True]]

 [[False  True  True  True  True]
  [ True  True  True  True  True]]]


In [15]:
b = a<10

print(b)

[[[ True  True  True  True  True]
  [False False False False False]]

 [[ True False False False False]
  [False False False False False]]]
